import React, { useState, useMemo } from 'react';
import { Header } from './components/Header';
import { SearchBar } from './components/SearchBar';
import { UniversityCard } from './components/UniversityCard';
import { MetricsDisplay } from './components/MetricsDisplay';
import { University } from './types/university';
import { useUniversities } from './hooks/useUniversities';

function App() {
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedUniversity, setSelectedUniversity] = useState<University | null>(null);
  const { data: universities, isLoading, error } = useUniversities();

  const filteredUniversities = useMemo(() => {
    if (!universities) return [];
    const query = searchQuery.toLowerCase();
    return universities.filter(university =>
      university.name.toLowerCase().includes(query) ||
      university.location.toLowerCase().includes(query)
    );
  }, [searchQuery, universities]);

  if (isLoading) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600"></div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <div className="text-red-600 text-center">
          <p className="text-xl font-semibold mb-2">Error loading universities</p>
          <p className="text-gray-600">Please try again later</p>
        </div>
      </div>
    );
  }

  const noResults = searchQuery && filteredUniversities.length === 0;

  return (
    <div className="min-h-screen bg-gray-50">
      <Header />
      
      <main className="container mx-auto px-4 py-12">
        <section className="mb-12">
          <h2 className="text-3xl font-bold text-gray-800 mb-8 text-center">
            Nigerian Universities Webometrics Ranking
          </h2>
          <SearchBar searchQuery={searchQuery} setSearchQuery={setSearchQuery} />
          
          {!selectedUniversity && (
            <>
              {noResults ? (
                <div className="text-center py-8">
                  <p className="text-gray-600 text-lg">
                    No universities found matching "{searchQuery}"
                  </p>
                  <button
                    onClick={() => setSearchQuery('')}
                    className="mt-4 text-blue-600 hover:text-blue-800"
                  >
                    Clear search
                  </button>
                </div>
              ) : (
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                  {filteredUniversities.map((university, index) => (
                    <UniversityCard
                      key={university.id}
                      university={university}
                      onSelect={setSelectedUniversity}
                      rank={index + 1}
                    />
                  ))}
                </div>
              )}
            </>
          )}

          {selectedUniversity && (
            <div className="space-y-6">
              <button
                onClick={() => setSelectedUniversity(null)}
                className="text-blue-600 hover:text-blue-800 flex items-center space-x-2 mb-6"
              >
                <span>← Back to rankings</span>
              </button>
              <MetricsDisplay university={selectedUniversity} />
            </div>
          )}
        </section>

        <section id="about" className="mb-12">
          <h2 className="text-2xl font-bold text-gray-800 mb-4">About Webometrics</h2>
          <div className="bg-white rounded-lg shadow-lg p-6">
            <p className="text-gray-600 leading-relaxed">
              Webometrics is a ranking system for universities based on their web presence and impact.
              The ranking is published by the Cybermetrics Lab, a research group belonging to the
              Consejo Superior de Investigaciones Científicas (CSIC) in Spain. The ranking aims to
              promote academic web presence and support Open Access initiatives for increasing the
              transfer of scientific and cultural knowledge generated by universities.
            </p>
            <div className="mt-4 p-4 bg-blue-50 rounded-lg">
              <h3 className="font-semibold text-blue-800 mb-2">Metrics Explanation:</h3>
              <ul className="list-disc list-inside space-y-2 text-gray-700">
                <li><strong>Presence (5%):</strong> Total number of web pages hosted in the main web domain of the university.</li>
                <li><strong>Visibility (50%):</strong> Number of external networks (subnets) linking to the institution's webpages.</li>
                <li><strong>Transparency (10%):</strong> Number of citations from Top authors according to Google Scholar citations.</li>
                <li><strong>Excellence (35%):</strong> Number of papers amongst the top 10% most cited in 26 disciplines.</li>
                <li><strong>Impact:</strong> Quality of the content evaluated through a "virtual referendum".</li>
                <li><strong>Openness:</strong> Global effort to set up institutional research repositories.</li>
              </ul>
            </div>
          </div>
        </section>
      </main>

      <footer className="bg-gray-800 text-white py-8">
        <div className="container mx-auto px-4 text-center">
          <p>&copy; {new Date().getFullYear()} Nigerian Universities Webometrics Dashboard. All rights reserved.</p>
        </div>
      </footer>
    </div>
  );
}

export default App;